import { Fundi, Shop, Event, Translation, SuperAgent } from "@/types";
import { SubscriptionStatus } from "@/types/payments";

export const mockFundis: Fundi[] = [
  {
    id: "1",
    name: "John Kamau",
    type: "fundi",
    email: "john.kamau@example.com",
    createdAt: "2023-01-10T10:00:00Z",
    specialty: "Electrician",
    city: "Dar es Salaam",
    rating: 4.8,
    reviewCount: 127,
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop",
    bio: "Certified electrician with 10+ years of experience in residential and commercial installations.",
    phone: "+255 712 345 678",
    whatsapp: "+255 712 345 678",
    verified: true,
    joinedDate: "2023-01-15"
  },
  {
    id: "2",
    name: "Amina Hassan",
    type: "fundi",
    email: "amina.hassan@example.com",
    createdAt: "2023-03-15T11:00:00Z",
    specialty: "Plumber",
    city: "Arusha",
    rating: 4.9,
    reviewCount: 98,
    image: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop",
    bio: "Expert plumber specializing in pipe installations, repairs, and water system maintenance.",
    phone: "+255 754 234 567",
    whatsapp: "+255 754 234 567",
    verified: true,
    joinedDate: "2023-03-20"
  },
  {
    id: "3",
    name: "David Mwangi",
    type: "fundi",
    email: "david.mwangi@example.com",
    createdAt: "2022-11-01T09:00:00Z",
    specialty: "Carpenter",
    city: "Mwanza",
    rating: 4.7,
    reviewCount: 156,
    image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop",
    bio: "Skilled carpenter crafting custom furniture and handling all woodwork projects.",
    phone: "+255 765 345 789",
    whatsapp: "+255 765 345 789",
    verified: true,
    joinedDate: "2022-11-10"
  }
];

export const mockShops: Shop[] = [
  {
    id: "shop1",
    name: "Dar Hardware Supplies",
    shopName: "Dar Hardware Supplies",
    city: "Dar es Salaam",
    rating: 4.6,
    reviewCount: 234,
    image: "https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=400&h=400&fit=crop",
    category: "Hardware Store",
    openingHours: "Mon-Sat: 8AM-6PM",
    phone: "+255 713 456 789",
    whatsapp: "+255 713 456 789",
    description: "Complete hardware supplies for construction and repairs. Quality tools and materials.",
    verified: true,
    businessRegistrationNumber: "BRELA-12345678",
    physicalAddress: "Nyerere Rd, Kinondoni, Dar es Salaam",
    verificationStatus: "approved",
    businessLicenseUrl: "/uploads/shop1-license.pdf",
    tinCertificateUrl: "/uploads/shop1-tin.pdf",
    storefrontPhotoUrl: "/uploads/shop1-storefront.jpg",
    trustPoints: 12,
    customerVerifications: 6,
    scamReports: 0,
    communityVerified: true,
    verifiedAt: "2025-10-15",
    phoneVerified: true,
  },
  {
    id: "shop2",
    name: "Arusha Tool Center",
    shopName: "Arusha Tool Center",
    city: "Arusha",
    rating: 4.8,
    reviewCount: 189,
    image: "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=400&h=400&fit=crop",
    category: "Tool Shop",
    openingHours: "Mon-Sat: 7:30AM-7PM",
    phone: "+255 756 567 890",
    whatsapp: "+255 756 567 890",
    description: "Professional tools and equipment for all trades. Expert advice available.",
    verified: true,
    businessRegistrationNumber: "BRELA-87654321",
    physicalAddress: "Sokoine Rd, Arusha",
    verificationStatus: "approved",
    storefrontPhotoUrl: "/uploads/shop2-storefront.jpg",
    trustPoints: 8,
    customerVerifications: 4,
    scamReports: 0,
    communityVerified: false,
    verifiedAt: "2025-11-01",
    phoneVerified: true,
  },
  {
    id: "shop3",
    name: "Mwanza Building Materials",
    shopName: "Mwanza Building Materials",
    city: "Mwanza",
    rating: 4.3,
    reviewCount: 87,
    image: "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?w=400&h=400&fit=crop",
    category: "Building Materials",
    openingHours: "Mon-Sat: 8AM-5PM",
    phone: "+255 745 123 456",
    whatsapp: "+255 745 123 456",
    description: "Quality cement, bricks, and construction materials.",
    verified: false,
    businessRegistrationNumber: "BRELA-45678901",
    physicalAddress: "Station Rd, Mwanza",
    verificationStatus: "pending",
    storefrontPhotoUrl: "/uploads/shop3-storefront.jpg",
    trustPoints: 2,
    customerVerifications: 1,
    scamReports: 0,
    communityVerified: false,
    phoneVerified: false,
  },
];

export const mockSuperAgents: SuperAgent[] = [
  {
    id: "sa1",
    userId: "user-sa1",
    name: "Joseph Mwambene",
    email: "joseph.mwambene@example.com",
    phone: "+255 754 123 456",
    photo: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop",
    region: "Dar es Salaam",
    district: "Kinondoni",
    ward: "Mikocheni",
    bio: "Experienced regional representative helping fundis and shops grow their businesses in Dar es Salaam.",
    fundisOnboarded: 45,
    shopsOnboarded: 12,
    totalCommissionEarned: 450000,
    subscriptionStatus: "active",
    subscriptionStartDate: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
    subscriptionEndDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    paymentMethod: "mpesa",
    lastPaymentDate: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
    lastPaymentAmount: 40000,
    verified: true,
    createdAt: new Date(Date.now() - 180 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "sa2",
    userId: "user-sa2",
    name: "Grace Kimaro",
    email: "grace.kimaro@example.com",
    phone: "+255 765 234 567",
    photo: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop",
    region: "Arusha",
    district: "Arusha City",
    bio: "Dedicated Super Agent connecting skilled fundis with customers across Arusha region.",
    fundisOnboarded: 32,
    shopsOnboarded: 8,
    totalCommissionEarned: 320000,
    subscriptionStatus: "active",
    subscriptionStartDate: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    subscriptionEndDate: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000).toISOString(),
    paymentMethod: "tigopesa",
    lastPaymentDate: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    lastPaymentAmount: 40000,
    verified: true,
    createdAt: new Date(Date.now() - 120 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "sa3",
    userId: "user-sa3",
    name: "Emmanuel Shayo",
    email: "emmanuel.shayo@example.com",
    phone: "+255 712 345 678",
    photo: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop",
    region: "Mwanza",
    district: "Nyamagana",
    bio: "Building the largest network of verified fundis in the Lake Zone.",
    fundisOnboarded: 28,
    shopsOnboarded: 6,
    totalCommissionEarned: 280000,
    subscriptionStatus: "active",
    subscriptionStartDate: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    subscriptionEndDate: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
    paymentMethod: "airtel",
    lastPaymentDate: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    lastPaymentAmount: 40000,
    verified: true,
    createdAt: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "sa4",
    userId: "user-sa4",
    name: "Fatuma Said",
    email: "fatuma.said@example.com",
    phone: "+255 783 456 789",
    region: "Dodoma",
    district: "Dodoma Urban",
    bio: "Helping the capital city find the best fundis.",
    fundisOnboarded: 15,
    shopsOnboarded: 4,
    totalCommissionEarned: 150000,
    subscriptionStatus: "expired",
    subscriptionStartDate: new Date(Date.now() - 35 * 24 * 60 * 60 * 1000).toISOString(),
    subscriptionEndDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    paymentMethod: "mpesa",
    lastPaymentDate: new Date(Date.now() - 35 * 24 * 60 * 60 * 1000).toISOString(),
    lastPaymentAmount: 40000,
    verified: true,
    createdAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const mockSubscriptionStatuses: SubscriptionStatus[] = [
  {
    userId: "1",
    userType: "fundi",
    isActive: true,
    expiryDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    isPromoted: true,
    promotionExpiry: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    lastPaymentDate: new Date().toISOString(),
    paymentMethod: "mpesa",
    transactionId: "MPESA123456"
  },
  {
    userId: "2",
    userType: "fundi",
    isActive: true,
    expiryDate: new Date(Date.now() + 25 * 24 * 60 * 60 * 1000).toISOString(),
    isPromoted: false,
    lastPaymentDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    paymentMethod: "stripe",
    transactionId: "STRIPE789012"
  },
  {
    userId: "3",
    userType: "fundi",
    isActive: true,
    expiryDate: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000).toISOString(),
    isPromoted: false,
    lastPaymentDate: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    paymentMethod: "mpesa",
    transactionId: "MPESA345678"
  },
  {
    userId: "shop1",
    userType: "shop",
    isActive: true,
    expiryDate: new Date(Date.now() + 28 * 24 * 60 * 60 * 1000).toISOString(),
    isPromoted: true,
    promotionExpiry: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    lastPaymentDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    paymentMethod: "mpesa",
    transactionId: "MPESA567890"
  },
  {
    userId: "shop2",
    userType: "shop",
    isActive: true,
    expiryDate: new Date(Date.now() + 22 * 24 * 60 * 60 * 1000).toISOString(),
    isPromoted: false,
    lastPaymentDate: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    paymentMethod: "stripe",
    transactionId: "STRIPE234567"
  }
];

export function initializeMockSubscriptions() {
  if (typeof window !== "undefined") {
    const existing = localStorage.getItem("smartfundi_subscriptions");
    if (!existing) {
      localStorage.setItem("smartfundi_subscriptions", JSON.stringify(mockSubscriptionStatuses));
      console.log("Initialized mock subscription data");
    }
  }
}

// Sample media messages for testing
export function initializeSampleMediaMessages() {
  if (typeof window !== "undefined") {
    const sampleMessages = [
      {
        id: "msg1",
        conversationId: "conv1",
        senderId: "customer1",
        receiverId: "1",
        text: "Hi, I need help with my electrical panel",
        timestamp: new Date(Date.now() - 3600000).toISOString(),
        read: true,
      },
      {
        id: "msg2",
        conversationId: "conv1",
        senderId: "customer1",
        receiverId: "1",
        text: "",
        timestamp: new Date(Date.now() - 3500000).toISOString(),
        read: true,
        mediaUrl: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800",
        mediaType: "image" as const,
        thumbnailUrl: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=200",
        fileSize: 245000,
      },
      {
        id: "msg3",
        conversationId: "conv1",
        senderId: "1",
        receiverId: "customer1",
        text: "I can see the issue. I'll need to replace that circuit breaker. When would be a good time for me to come over?",
        timestamp: new Date(Date.now() - 3400000).toISOString(),
        read: true,
      },
    ];

    const existing = localStorage.getItem("chat_conv1");
    if (!existing) {
      localStorage.setItem("chat_conv1", JSON.stringify(sampleMessages));
      console.log("Initialized sample media messages");
    }
  }
}

export const mockEvents: Event[] = [
  {
    id: "e1",
    title: {
      en: "Tanzania Construction Technology Expo 2025",
      sw: "Maonyesho ya Teknolojia ya Ujenzi Tanzania 2025",
    },
    description: {
      en: "Annual exhibition showcasing the latest construction tools, materials, and techniques for professionals across Tanzania.",
      sw: "Maonyesho ya kila mwaka yanayoonyesha zana za hivi karibuni za ujenzi, vifaa, na mbinu kwa wataalamu nchini Tanzania.",
    },
    organizer: "Tanzania Builders Association",
    location: "Diamond Jubilee Hall, Dar es Salaam",
    date: new Date(Date.now() + 15 * 86400000).toISOString(),
    time: "9:00 AM - 5:00 PM",
    isSponsored: true,
    imageUrl: `https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?q=80&w=2053&auto=format&fit=crop`,
    expectedAttendees: 500,
  },
  {
    id: "e2",
    title: {
      en: "Electrical Safety Training Workshop",
      sw: "Warsha ya Mafunzo ya Usalama wa Umeme",
    },
    description: {
      en: "Free training workshop on electrical safety standards and best practices for electricians and apprentices.",
      sw: "Warsha ya bure ya mafunzo kuhusu viwango vya usalama wa umeme na mbinu bora kwa wafundi umeme na wanafunzi.",
    },
    organizer: "Tanzania Electrical Institute",
    location: "Vocational Training Center, Arusha",
    date: new Date(Date.now() + 8 * 86400000).toISOString(),
    time: "10:00 AM - 1:00 PM",
    isSponsored: false,
    imageUrl: `https://images.unsplash.com/photo-1581092921462-6849a6e3a453?q=80&w=2070&auto=format&fit=crop`,
    expectedAttendees: 50,
  },
  {
    id: "e3",
    title: {
      en: "Automotive Repair Skills Fair",
      sw: "Maonyesho ya Ujuzi wa Urekebishaji wa Magari",
    },
    description: {
      en: "Meet industry experts, learn new techniques, and discover the latest automotive tools and diagnostic equipment.",
      sw: "Kutana na wataalamu wa sekta, jifunze mbinu mpya, na gundua zana za hivi karibuni za magari na vifaa vya uchunguzi.",
    },
    organizer: "Tanzania Automotive Association",
    location: "Mlimani City Conference Center, Dar es Salaam",
    date: new Date(Date.now() + 22 * 86400000).toISOString(),
    time: "8:30 AM - 6:00 PM",
    isSponsored: true,
    imageUrl: `https://images.unsplash.com/photo-1553775282-20af807797d2?q=80&w=2070&auto=format&fit=crop`,
    expectedAttendees: 300,
  },
];
