
import { Fundi, Shop, Event } from "@/types";

export const mockFundis: Fundi[] = [
  {
    id: "f1",
    type: "fundi",
    name: "John Mwangi",
    email: "john@example.com",
    phone: "+255712345678",
    photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=John",
    specialty: "Electrician",
    city: "Dar es Salaam",
    bio: "Expert electrician with 10 years of experience in residential and commercial installations.",
    whatsapp: "+255712345678",
    verified: true,
    rating: 4.8,
    reviewCount: 124,
    subscriptionActive: true,
    promoted: true,
    promotedUntil: new Date(Date.now() + 86400000).toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "f2",
    type: "fundi",
    name: "Grace Mollel",
    email: "grace@example.com",
    phone: "+255723456789",
    photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=Grace",
    specialty: "Plumber",
    city: "Arusha",
    bio: "Specialized in modern plumbing systems and water treatment solutions.",
    verified: true,
    rating: 4.9,
    reviewCount: 98,
    subscriptionActive: true,
    promoted: true,
    promotedUntil: new Date(Date.now() + 86400000).toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "f3",
    type: "fundi",
    name: "Hassan Kimaro",
    email: "hassan@example.com",
    phone: "+255734567890",
    photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=Hassan",
    specialty: "Carpenter",
    city: "Mwanza",
    bio: "Custom furniture maker and general carpentry services.",
    whatsapp: "+255734567890",
    verified: true,
    rating: 4.7,
    reviewCount: 156,
    subscriptionActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "f4",
    type: "fundi",
    name: "Sarah Njau",
    email: "sarah@example.com",
    phone: "+255745678901",
    photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah",
    specialty: "Mechanic",
    city: "Dodoma",
    bio: "Automotive repair specialist with focus on Japanese and European cars.",
    verified: true,
    rating: 4.6,
    reviewCount: 87,
    subscriptionActive: true,
    promoted: true,
    promotedUntil: new Date(Date.now() + 86400000).toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "f5",
    type: "fundi",
    name: "David Mtui",
    email: "david@example.com",
    phone: "+255756789012",
    photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=David",
    specialty: "Welder",
    city: "Dar es Salaam",
    bio: "Metal fabrication and welding for construction and industrial projects.",
    whatsapp: "+255756789012",
    verified: true,
    rating: 4.8,
    reviewCount: 72,
    subscriptionActive: true,
    createdAt: new Date().toISOString(),
  },
];

export const mockShops: Shop[] = [
  {
    id: "s1",
    type: "shop",
    name: "Juma Hardware",
    email: "info@jumahardware.co.tz",
    phone: "+255767890123",
    shopName: "Juma Hardware & Tools",
    logo: "https://api.dicebear.com/7.x/initials/svg?seed=JH&backgroundColor=2563eb",
    city: "Dar es Salaam",
    ward: "Kariakoo",
    categories: ["Tools", "Paint", "Hardware", "Building Materials"],
    openingHours: "8:00 AM - 6:00 PM",
    whatsapp: "+255767890123",
    verified: true,
    rating: 4.7,
    reviewCount: 203,
    subscriptionActive: true,
    promoted: true,
    promotedUntil: new Date(Date.now() + 86400000).toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "s2",
    type: "shop",
    name: "Arusha Electrical Supplies",
    email: "info@arushaelectric.co.tz",
    phone: "+255778901234",
    shopName: "Arusha Electrical Supplies",
    logo: "https://api.dicebear.com/7.x/initials/svg?seed=AE&backgroundColor=fb923c",
    city: "Arusha",
    ward: "Central",
    categories: ["Electrical", "Lighting", "Cables", "Switches"],
    openingHours: "7:30 AM - 7:00 PM",
    verified: true,
    rating: 4.8,
    reviewCount: 167,
    subscriptionActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "s3",
    type: "shop",
    name: "Mwanza Auto Parts",
    email: "sales@mwanzaauto.co.tz",
    phone: "+255789012345",
    shopName: "Mwanza Auto Parts Center",
    logo: "https://api.dicebear.com/7.x/initials/svg?seed=MA&backgroundColor=16a34a",
    city: "Mwanza",
    ward: "Isamilo",
    categories: ["Auto Parts", "Lubricants", "Batteries", "Accessories"],
    openingHours: "8:00 AM - 8:00 PM",
    whatsapp: "+255789012345",
    verified: true,
    rating: 4.6,
    reviewCount: 134,
    subscriptionActive: true,
    promoted: true,
    promotedUntil: new Date(Date.now() + 86400000).toISOString(),
    createdAt: new Date().toISOString(),
  },
];

export const mockEvents: Event[] = [
  {
    id: "e1",
    title: {
      en: "Tanzania Construction Technology Expo 2025",
      sw: "Maonyesho ya Teknolojia ya Ujenzi Tanzania 2025",
    },
    description: {
      en: "Annual exhibition showcasing the latest construction tools, materials, and techniques for professionals across Tanzania.",
      sw: "Maonyesho ya kila mwaka yanayoonyesha zana za hivi karibuni za ujenzi, vifaa, na mbinu kwa wataalamu nchini Tanzania.",
    },
    organizerName: "Tanzania Builders Association",
    location: "Diamond Jubilee Hall, Dar es Salaam",
    date: new Date(Date.now() + 15 * 86400000).toISOString(),
    sponsored: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "e2",
    title: {
      en: "Electrical Safety Training Workshop",
      sw: "Warsha ya Mafunzo ya Usalama wa Umeme",
    },
    description: {
      en: "Free training workshop on electrical safety standards and best practices for electricians and apprentices.",
      sw: "Warsha ya bure ya mafunzo kuhusu viwango vya usalama wa umeme na mbinu bora kwa wafundi umeme na wanafunzi.",
    },
    organizerName: "Tanzania Electrical Institute",
    location: "Vocational Training Center, Arusha",
    date: new Date(Date.now() + 8 * 86400000).toISOString(),
    sponsored: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "e3",
    title: {
      en: "Automotive Repair Skills Fair",
      sw: "Maonyesho ya Ujuzi wa Urekebishaji wa Magari",
    },
    description: {
      en: "Meet industry experts, learn new techniques, and discover the latest automotive tools and diagnostic equipment.",
      sw: "Kutana na wataalamu wa sekta, jifunze mbinu mpya, na gundua zana za hivi karibuni za magari na vifaa vya uchunguzi.",
    },
    organizerName: "Tanzania Automotive Association",
    location: "Mlimani City Conference Center, Dar es Salaam",
    date: new Date(Date.now() + 22 * 86400000).toISOString(),
    sponsored: true,
    createdAt: new Date().toISOString(),
  },
];
